### ISSUE TITLE
SYCL 2020 make_module API definition is incorrect

### ISSUE THREAD

**Issue by kbobrovs** [KhronosGroup/SYCL-Docs#105]
[SYCL 2020](https://www.khronos.org/registry/SYCL/specs/sycl-2020-provisional.pdf) provisional spec defines make_module API as follows:
```cpp
template<backend Backend>
kernel make_module(const backend_traits<Backend>::native_type<event> &backendObject, const context &targetContext);
```
Instead it should apparently be:
```cpp
template<backend Backend>
module make_module(const backend_traits<Backend>::native_type<module> &backendObject, const context &targetContext);
```

**Comment by gmlueck** [comment]
This problem raised in this issue no longer exists.  There is no longer any API named `make_module` and the similar `make_kernel_bundle()` does not have this problem.

@keryell: I don't have permission to close issues in this repo.  Can you close this?

**Comment by keryell** [comment]
Thanks.
