### ISSUE TITLE
Wrong description with image class constructors.

### ISSUE THREAD

**Issue by AA11BB22** [KhronosGroup/SYCL-Docs#106]
I believe the following constructors' description have been misplaced and should be swapped.

https://github.com/KhronosGroup/SYCL-Docs/blob/SYCL-1.2.1/final-rev7/latex/programming_interface.tex#L1858-L1873

https://github.com/KhronosGroup/SYCL-Docs/blob/SYCL-1.2.1/final-rev7/latex/programming_interface.tex#L1891-L1905

**Comment by keryell** [comment]
Good catch! The allocator versions have been swapped. :-(
This has been fixed in SYCL 2020, with a slightly different API https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_unsampled_image_interface

I suggest we close this, since SYCL 1.2.1 is no longer supported.
Thanks.
