### ISSUE TITLE
SYCL 2020 Specification

### ISSUE THREAD

**Issue by arkantos493** [KhronosGroup/SYCL-Docs#114]
Are there any plans to also publish the SYCL 2020 specification document here?
So people could change small mistakes and make pull request for the new standard document.

(For example: I found a wrongly colored brace. Not a major problem, but easily fixable if the standard would be released here.)

**Comment by keryell** [comment]
Yes, we are planning about pushing the SYCL 2020 branch soon.
The question is just to decide how much we clean up the history.
So, keep your typo list ready.
Thanks.

**Comment by keryell** [comment]
It is open-source now.
