### ISSUE TITLE
Unary plus and minus operators for sycl::vec takes a non-const reference to the value

### ISSUE THREAD

**Issue by mujjingun** [KhronosGroup/SYCL-Docs#115]
From SYCL 2020 specification (revision 2) page 351:

```cpp
// OP is unary +, -
friend vec operatorOP(vec &rhs) const { /* ... */ }
```

Is there a reason why this takes a non-const lvalue reference? This makes it impossible to do something like:

```cpp
const sycl::float4 v{};
-v; // Error: cannot bind const vec& to vec&
```

or 

```cpp
-sycl::float4{}; // Error: cannot bind vec&& to vec&
```

In my opinion, the line in the spec should be corrected to:

```cpp
// OP is unary +, -
friend vec operatorOP(const vec &val) { /* ... */ }
```

**Comment by tomdeakin** [comment]
Fixed in #118

**Comment by mujjingun** [comment]
@tomdeakin Shouldn't the `const` qualifier *after* the function signature be removed too? It doesn't make sense to have it in a non-member friend function.

**Comment by tomdeakin** [comment]
Good catch, I'll re-open the PR.

**Comment by keryell** [comment]
I think this is fixed now.
