### ISSUE TITLE
Allow for capturing tuple types in SYCL kernels

### ISSUE THREAD

**Issue by j-stephan** [KhronosGroup/SYCL-Docs#12]
### The Problem

The SYCL specification demands that all data structures passed into a kernel are standard layout classes. This prevents most widely-used tuple types (`std::tuple`, `boost::hana::tuple`, etc.) from being passed, effectively disabling generic kernels with variadic parameters. In turn, this makes the implementation of a SYCL backend for abstract kernel libraries such as [Alpaka](https://github.com/ComputationalRadiationPhysics/alpaka) or [HPX](https://github.com/STEllAR-GROUP/hpx), both heavily using variadic kernels, nearly impossible. HPX stumbled upon this a few years ago (see [this paper](http://stellar.cct.lsu.edu/pubs/copik_iwocl_2017_sycl_for_hpx_compute.pdf), Section 4.4) and ultimately failed as there is still no SYCL backend (as far as I know).

### Example

```c++
template <typename Func, typename... Args>
struct generic_kernel
{
    Func m_kernel;
    std::tuple<Args...> m_args;

    generic_kernel(Func&& kernel, Args...&& args)
    : m_kernel{kernel}, m_args{args...}
    {}

    auto operator()(cl::sycl::handler& cgh)
    {
        // copy by value to prevent 'this' pointer in device code
        auto k_kernel = m_kernel;
        auto k_args = m_args;

        cgh.single_task<class dummy>([=]()
        {
            // Error: class std::tuple is not standard layout
            std::apply(k_kernel, k_args);
        }
    }
};                                                                                                                                      

```

### Use case

Libraries such as [Alpaka](https://github.com/ComputationalRadiationPhysics/alpaka) or [HPX](https://github.com/STEllAR-GROUP/hpx) store their (abstract) kernel arguments in the form of variadic parameter packs which are saved in a `tuple` inside their (abstract) kernel structure. The actual (SYCL, CUDA...) kernel function itself is then called via `std::apply` or similar mechanisms. This approach already works for CUDA and it would be great to achieve the same with SYCL.

Users might also define their own generic kernel structs (launched with the same set of global sizes / work-group sizes) for a set of similar functions with differing behaviour (e.g. a set of filter kernels).

### Possible solutions

1. Lower the restrictions for kernel parameters so `std::tuple` et al. can be captured.
2. Implement a SYCL `tuple` (maybe with conversion from `std::tuple`) which is able to be passed into SYCL kernels.

**Comment by tdd11235813** [comment]
From the issues @j-stephan reported so far, this one is crucial and urgent. We need to know at least how to modify the tuple implementation into a SYCL-conformant way, so we have a workaround in time.
Maybe you see another way we can try out, this would be highly appreciated.

**Comment by Ruyk** [comment]
We have a standard-layout tuple implementation in our SDK, https://github.com/codeplaysoftware/computecpp-sdk/blob/master/include/stl-tuple/STLTuple.hpp

**Comment by tdd11235813** [comment]
awesome, we will try out, thanks a lot for the quick reply.

**Comment by j-stephan** [comment]
The Codeplay tuple works fine for our purposes. Thanks for the hint!
