### ISSUE TITLE
SYCL 2020 accessors issues.

### ISSUE THREAD

**Issue by bader** [KhronosGroup/SYCL-Docs#126]
Here is the summary of discussion between @gmlueck and @yuriykoch regarding issues in accessors section of SYCL 2020 specification.

1) An accessor with deprecated target `local` has method `is_placeholder()`. But there was no such method for local accessor in SYCL 1.2.1. We should remove this method from SYCL 2020 specification.

2) Par. 3.13.3 states that: 
    “Inside kernels, the functions and data types available are restricted by the underlying capabilities of SYCL backend devices.”

    That statement from section [3.13.3](https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#_functions_and_data_types_available_in_kernels) is not very useful because it doesn’t explain how an application can tell which data types are restricted by the backend.  We describe this better, though, in other parts of the spec.  For example, [4.6.4.3](https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:device-aspects) states that the “sycl::half” type is only available on a device if the device has “aspect::fp16”. We suggest removing 3.13.3 paragraph.

3) local_accessor description states that: “The underlying dataT type can be any C++ type”. 

    We suggest changing this sentence to “The underlying dataT type can be any C++ type that the device supports.”

    The intent is to say that local accessors do not impose any further restrictions on the underlying type beyond those restrictions on the device code in general.

4) Accessor API changes missing in "What has changed ..." section. Looks like D.1 appendix may be extended with the following:
* There is no explicit mention of `accessor::value_type` and `accessor::reference` type dependency on the access mode. The spec says “Member functions of accessor which return a reference to an element have been changed to return a const reference for read-only accessors.”, but we should tweak that sentence to say that the member types are also changed for read-only accessors.

* There is no explicit mention of read_write access mode removal for image accessors. Even SYCL 1.2.1 did not allow read-write access mode for images, unless the target was “host_image”.  It was probably an oversight that “host_unsampled_image_accessor” does not provide this ability.

5) p. 180, get_range() description for the target ‘local’ has misprint:
                “the returned value is the the range”

**Comment by gmlueck** [comment]
I think the issues reported here are addressed in the following PRs:

* #124
* #127
* #128
* #129

We can close this issue when those PRs are merged.

**Comment by bader** [comment]
> I think the issues reported here are addressed in the following PRs:
> 
> * #124
> * #127
> * #128
> * #129
> 
> We can close this issue when those PRs are merged.

All these PRs are merged. Closing the issue.
