### ISSUE TITLE
Error in `https://www.khronos.org/files/sycl/sycl-2020-reference-guide.pdf`

### ISSUE THREAD

**Issue by TApplencourt** [KhronosGroup/SYCL-Docs#141]
In the example Page 1 we have
`accessor writeResult { resultBuf, cgh, write_only, no_init };`

It should be:
`accessor writeResult { resultBuf, cgh, write_only, noinit };`

(without the `_`)

**Comment by keryell** [comment]
Actually we made the change in the spec to follow the usual `_` coding style.
So, as you closed it, it was not a bug in the reference guide.

**Comment by TApplencourt** [comment]
> So, as you closed it, it was not a bug in the reference guide.

Exactly. It was a mistake on my side to check the SYCL 2020 provisional spec and not the officially released one. I guess now, I know what changed between the provisional and the final one.  
Sorry about the noise!
