### ISSUE TITLE
Attribute documentation does not describe default values

### ISSUE THREAD

**Issue by AaronBallman** [KhronosGroup/SYCL-Docs#142]
The SYCL 2020 specification has some attributes with default values listed in https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#table.kernel.attributes (specifically: `reqd_work_group_size` and `work_group_size_hint`), but it doesn't describe what the default values are when the user elides the argument. I presume them to be `1`, but the specification should list the values explicitly.

**Comment by gmlueck** [comment]
I do not think there are any default values to these attribute arguments.  These attributes are defined with three forms: a 1-argument form, a 2-argument form, and a 3-argument form.  The application is required to use the form that matches the dimensionality of the kernel.  From the description of `reqd_work_group_size()` [here](https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#table.kernel.attributes):

> The dimensionality of the attribute variant used must match the dimensionality of the work-group used to invoke the kernel.

When the application uses the 1- or 2-argument form, the other arguments just don't exist.  It's not the case that they take some default value.

**Comment by AaronBallman** [comment]
So you expect implementations to have three distinct attributes for the same concept, but with different parameter arity? That opens up even more implementation questions for me, such as whether this code is valid:
```
[[sycl::reqd_work_group_size(4, 1)]] void foo();
[[sycl::reqd_work_group_size(4)]] void foo();
```
(My understanding was that this is valid code where the redeclaration carries the same information, but based on what you wrote here it sounds like you'd expect a diagnostic.)

**Comment by gmlueck** [comment]
Yes, that code is invalid for two reasons:

* We have a blanket statement saying that you cannot have two instances of the same attribute with different parameters:

  > Unless an attribute’s description specifically allows it, a kernel or device function may not be declared
with the more than one instance of the same attribute unless all instances have the same attribute arguments. The compiler must issue a diagnostic for programs which violate this requirement. 

* The kernel function `foo()` has some fixed dimensionality.  It cannot be both 1-dimensional and 2-dimensional, so one of the attributes in your example has the wrong number of dimensions for that kernel, violating:

  > The dimensionality of the attribute variant used must match the dimensionality of the work-group used to invoke the kernel.

**Comment by AaronBallman** [comment]
Good to know, thank you for the clarification.

**Comment by fraggamuffin** [comment]
will track down PR that fixed this

**Comment by fraggamuffin** [comment]
!235

**Comment by fraggamuffin** [comment]
#235
