### ISSUE TITLE
Expand interface of sycl::buffer::get_access to accept property lists

### ISSUE THREAD

**Issue by mabraham** [KhronosGroup/SYCL-Docs#179]
The use of `sycl::access::mode::discard_write` is deprecated in favor of `sycl::property::no_init` (https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#_discard_access_modes).

To encourage this change of usage, the `sycl::buffer::get_access` convenience methods (https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#_buffer_interface) should be changed to be able to accept a property list, so that one does not have to use an explicit `sycl::accessor` construction for the cases where the `no_init` property should be used. `sycl::accessor` constructors do accept property lists, viz https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#_interface_for_buffer_command_accessors.

**Comment by keryell** [comment]
Thanks for the feedback.
There is an on-going generalization of properties used in various contexts, so I guess we can add also properties in this context.

**Comment by ProGTX** [comment]
Hi, we believe your use case should be possible by using the variadic `get_access` function, which just forwards the arguments to the accessor constructor (see `auto get_access(Ts...)` in the section you linked).

Example:

```cpp
auto acc = buf.get_access(cgh, sycl::property::no_init);
```

**Comment by mabraham** [comment]
Yes I now agree. I learned this in the meantime but forgot to post here. Thanks!
