### ISSUE TITLE
Exceptions inside `host_task`

### ISSUE THREAD

**Issue by psalz** [KhronosGroup/SYCL-Docs#214]
The SYCL API prescribes scenarios where an exception must be thrown inside a `host_task`, for example calling `interop_handle::get_native_mem` on a placeholder accessor.  Is the intent here that users always catch these explicitly? What happens if an exception is not caught? Will it be reported through the async handler? Will it be swallowed?

Furthermore, what happens if user code throws an exception? It is not clear to me whether all asynchronous errors must also be derived from `sycl::exception`, which would make reporting user exceptions through the async handler problematic.

FWIW, ComputeCpp 2.8 seems to swallow exceptions, whereas DPC++ reports them through the async handler.

**Comment by keryell** [comment]
I like the idea of propagating the exception instead of a blunt `std::terminate`. But then any kind of exception should be allowed, not only `sycl::exception`.

**Comment by fraggamuffin** [comment]
Drafting
