### ISSUE TITLE
Clarify what happens when multiple commands are submitted in a single CGF

### ISSUE THREAD

**Issue by psalz** [KhronosGroup/SYCL-Docs#223]
Section "4.9.3 Command group scope" states:

> A command group scope, as defined in Section 3.7.1, may execute a single command such as invoking a
kernel, copying memory, or executing a host task. It is legal for a command group scope to statically contain
more than one call to a command function, but any single execution of the command group function
object may execute no more than one command.

There is however no mention about what happens when a user *does* try to execute multiple commands in a single CGF. I also could not find any other location talking about this (although I may have missed something). In any case, I think this paragraph should be extended to mention that a synchronous exception will be thrown, either with `ercc:invalid` or even a new error code.

**Comment by fraggamuffin** [comment]
discussed, in drafting
