### ISSUE TITLE
Clarification request regarding the semantics of sycl::atomic_ref<>::operator+=() 

### ISSUE THREAD

**Issue by mreineck** [KhronosGroup/SYCL-Docs#227]
The current SYCL specification states in "4.15.3 Atomic references" that the semantics of `sycl::atomic_ref<>::fetch_add()` and `sycl::atomic_ref<>::operator+=()` are equivalent. This is at odds with the standard C++ counterparts, where `fetch_add()` returns the value of the reference _before_ the addition, and `operator+=()` returns the value _after_ the addition has taken place.

Is this difference deliberate? If so, I propose to state this explicitly in the specification, since otherwise inadvertent mistakes will most likely happen.
On the other hand, it is not obvious to me why there should be an `operator+=()` which does not match its C++ counterpart, if exactly the same functionality is available via `fetch_add`. Simply omitting `operator+=()` may be a less confusing option.

The situation for `fetch_sub` and `operator-=()` is analogous.

**Comment by Pennycook** [comment]
> Thanks for looking into this!
> 
> BTW, is there a place to submit things that are not outright bugs, but more "wish list"? (For example it seems that SYCL 2020 only specifies `abs` for integer types, but not floating point types, which can also come as a nasty surprise to people used to `std::abs`, which deals with integer and floating point types.)

Thank you for reporting it! :)

@keryell, @tomdeakin: Is there a better place than here for "wish list" issues?

**Comment by fraggamuffin** [comment]
PR exists
