### ISSUE TITLE
 SYCL functions for explicit memory operations

### ISSUE THREAD

**Issue by keryell** [KhronosGroup/SYCL-Docs#23]
While working on implementation of these functions for https://github.com/triSYCL/triSYCL/issues/66, I found the semantics unclear, specially concerning the transfers accessors to accessors.
Do we consider that we use the `get_linear_id()` to access the source?
If so, there is no constrains to have accessors of the same rank on source and destination.
Should we really have the same target, mode and value type as specified today?

There is also some destination/source inversions fixed in https://github.com/KhronosGroup/SYCL-Docs/pull/22

**Comment by j-stephan** [comment]
Wouldn't this break 2D memory layouts on GPUs? NVIDIA GPUs add additional bytes to the rows of 2D (and 3D) allocations to ensure optimized memory accesses, I assume AMD and Intel GPUs do something similar. Copying by relying on `get_linear_id()` would likely cause some trouble in this case, unless I'm missing something.

**Comment by keryell** [comment]
Anyway copying from `src[i][j][k]` to `dst[i][j][k]` is not a dense copy if `src` and `dst` do not have the same size.

**Comment by psalz** [comment]
See also the discussion for my implementation of explicit memory operations in hipSYCL: https://github.com/illuhad/hipSYCL/pull/39

**Comment by keryell** [comment]
@psalz yes it looks like anyone trying to implement it should encounter the same problem... :-/

**Comment by bader** [comment]
https://github.com/KhronosGroup/SYCL-Docs/commit/5c3fd1be1916b8dfb196de2041c9afd31b6ec0bd allows different target, mode and value type for src and dst accessors of copy methods.

**Comment by bader** [comment]
SYCL WG: decided to close this issues as it mostly addressed by https://github.com/KhronosGroup/SYCL-Docs/commit/5c3fd1be1916b8dfb196de2041c9afd31b6ec0bd and continue discussion on further clarifications internally.
