### ISSUE TITLE
`Host Prefetch`

### ISSUE THREAD

**Issue by TApplencourt** [KhronosGroup/SYCL-Docs#277]
When using USM (`sycl::malloc_shared`), one may want to use `prefetch` to potentially transfer data from the host to the device. 

Are we missing the reverse operation (sending the data from the device to the host)? 

It exists in CUDA via [cudaMemPrefetchAsync](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1ge8dc9199943d421bc8bc7f473df12e42):
> Passing in cudaCpuDeviceId for dstDevice will prefetch the data to host memory

And in OpenCL (kind of, it's stronger than a prefetch) via [clEnqueueMigrateMemObjects](https://registry.khronos.org/OpenCL/sdk/1.2/docs/man/xhtml/clEnqueueMigrateMemObjects.html) / clEnqueueSVMMigrateMem(https://registry.khronos.org/OpenCL/sdk/2.2/docs/man/html/clEnqueueSVMMigrateMem.html)

>CL_MIGRATE_MEM_OBJECT_HOST:  This flag indicates that the specified set of memory objects are to be migrated to the host, regardless of the target command queue.

**Comment by TApplencourt** [comment]
It's good that you have an extension. That means it's important to support the feature :D

We may want to be future-proof to do USM from Device -> Device.  This is why I didn't go through the `prefetch_host()` strategy.
And also `sycl::host_selector{}` is now optional in SYCL2020 no?

**Comment by illuhad** [comment]
Can we not express device->device in exactly the same way, by just having a prefetch operation submitted to a queue bound to the device to which you want to prefetch?
`prefetch_host()` is probably a more common scenario so it maybe makes sense to have a shortcut there.

> And also sycl::host_selector{} is now optional in SYCL2020 no?

Maybe, but it also works with `cpu_selector`, that's the same thing in hipSYCL ;)

**Comment by TApplencourt** [comment]
>Can we not express device->device in exactly the same way, by just having a prefetch operation submitted to a queue bound to the device to which you want to prefetch?

![image](https://user-images.githubusercontent.com/6524907/186212267-f02303db-e8c0-4dfd-9dbc-50c2aa83b1f4.png)

You are right `prefetch_host` seems a natural way. I agree!
