### ISSUE TITLE
Clarify if swizzling vec<T, N> to vec<T, N-n> should be possible

### ISSUE THREAD

**Issue by fodinabor** [KhronosGroup/SYCL-Docs#29]
Currently it is not clear if simple swizzles of a `vec<T, 4>` should include swizzles for smaller vector types, like: `.xyz()`
As stated in the spec in section 4.10.2.1 in the description for XYZW_SWIZZLE:

> [...] Where XYZW_SWIZZLE is all permutations with repetition of x, y for numElements == 2, x, y, z for numElements == 3 and x, y, z, w for numElements == 4. For example xzyw and xyyy

Please clarify.

Also see: illuhad/hipSYCL#7

**Comment by AerialMantis** [comment]
It is intended that the simple swizzles `XYZW_SWIZZLE` and `RGBA_SWIZZLE`  include permutations of fewer elements than the size of the original vector. So the following code should be legal:
```
vec<float, 4> f4{1.0f, 2.0f, 3.0f, 4.0f};
vec<float, 2> f2 = f4.xz();
```

However, reading the specification now I can see why this is not clear so I will prepare a pull request to clarify this.

**Comment by fodinabor** [comment]
Ok, thank you for the clarification!
