### ISSUE TITLE
Searching broken within spec PDF output

### ISSUE THREAD

**Issue by mkinsner** [KhronosGroup/SYCL-Docs#3]
I've heard that people are having trouble searching for text within the SYCL 1.2.1 spec PDF.  Some of the issues appear to be on Mac specifically, but others are cross-platform.   The problem may be related to underscores - that's where there are known reproductions.

**Problem 1:** Searching for italicized text with an underscore misses matches, even on a PDF reader under Windows.  For example, SYCL1.2.1r5, p.76, the table has _cl_command_queue_info_ in the right column.  I can't make my PDF reader find any portion of the text, once I add an underscore to it.

**Problem 2:** Non-italicized hits missing on some Mac readers (Safari/Preview).  A reproducer of the problem is async_handler.  Searching with Safari/Preview on Mac apparently finds 8 results, while Acrobat reader on Mac finds 33 (which is consistent with what I see with a different reader in Windows).

**Comment by oddhack** [comment]
We dealt with this in the GL specs as well. I have a vague recollection that the {underscore} package helped, but it's been a long time and I'm not certain.

**Comment by keryell** [comment]
I am working on it... Several issues...

**Comment by keryell** [comment]
Making some progress... "async_handler" now in Ubuntu Okular or Windows Acrobat reader is found 42 times instead of 33, but only 6 times by Mac Preview...
"cl_command_queue_info" is now found by the 3 tools.
Perhaps PDF support is deprecated on Mac and there is a new format to use. That would not surprise me as that sounds familiar...
Still diving...

**Comment by keryell** [comment]
The current situation seems quite better.
Now there are *43* instances of `async_handler` found.

On the crazy part on Mac OS X:
- MacOS X Preview 10.1 (944.6.16.1) find the 43 instances, but when I change the PDF in its back, it just crashes;
- Safari 12.1.1 (14607.2.6.1.1) can somehow find all the 43 occurrences, but actually 33 are found
while searching forward while 10 are found while searching backward... :-( I find this... awkward :-) I would like to program this bug, I would not know how to do it... :-(

If there are people using Mac OS X who want to open some bug reports, go for it.
I prefer using Linux in the meantime... :-)
