### ISSUE TITLE
Clarify blocking behavior of `queue::submit`

### ISSUE THREAD

**Issue by psalz** [KhronosGroup/SYCL-Docs#307]
There seems to be a typo in the current wording regarding the behavior of `queue::submit` in section 4.6.5 (emphasis mine):

> The submit member function schedules ` command groups` **asynchronously**, so any errors in the submission of a `command group` are handled by throwing **synchronous** SYCL exceptions.

I assume the intent here was to say ~command groups~ (edit: command group function objects) are scheduled *synchronously*. Furthermore, I couldn't find any information on whether the CGF is guaranteed to be executed in the thread that calls `queue::submit`. While fixing the wording above would somewhat imply this, the word "schedule" could also mean "may run in a different thread but completes before the call to `queue::submit` returns".

I did a quick check and it looks like ComputeCpp, DPC++ and hipSYCL currently all run the CGF in the calling thread. This is the less surprising (and dangerous) behavior and should be codified in the spec, in my opinion.

**Comment by tomdeakin** [comment]
I think the intent is that `queue::submit()` is an asynchronous call; i.e. does not wait for the kernel/command to finish executing before returning. The command group function contains within in a command, and we want that command to be scheduled asynchronously.

There was recent clarification about the word "kernel" vs "command" in #301, so maybe the wording should be:

> The submit member function executes the command group function (as described in §3.7.1.2) and schedules commands ~groups~ **asynchronously**, so any errors in the submission of a command group are handled by throwing **synchronous** SYCL exceptions.

**Comment by psalz** [comment]
Right, I think I read "command group" as "command group function object". In general the spec is a bit fuzzy on the distinction between the two, and section 3.7.1.2 frequently uses the term "command group object", which seems to be something in between.

Additionally I find the word "so" in "so any errors in the submission [...]" confusing, because it seems to imply that one naturally follows from the other, which IMO it doesn't.

>> The submit member function executes the command group function (as described in §3.7.1.2) and schedules commands ~groups~ asynchronously, so any errors in the submission of a command group are handled by throwing synchronous SYCL exceptions.

I like the clarification but I think we should probably stick with "command group", as we mean to say that both the command and all of its required data tranfers are processed asynchronously. Also I'd still like to get the threading clarification in there (if people agree), so maybe something like:

> The submit member function synchronously executes the provided command group function object (as described in §3.7.1.2) in the calling thread, thereby scheduling a command group for asynchronous execution. Any errors in the submission of a command group are handled by throwing synchronous SYCL exceptions.

**Comment by gmlueck** [comment]
I think @psalz's proposed text is a good clarification, but I'd change the last sentence slightly:

> The submit member function synchronously invokes the provided command group function object (as described in §3.7.1.2) in the calling thread, thereby scheduling a command group for asynchronous execution. Any error in the submission of a command group is handled by throwing a synchronous SYCL exception.

I just changed it to be singular vs. plural.  It's not possible for a single `submit` call to throw more than one synchronous exception, so using singular seems clearer.

FWIW, the terms "command group" and "command group function object" are both glossary terms, and the glossary describes the distinction.

**Comment by psalz** [comment]
> FWIW, the terms "command group" and "command group function object" are both glossary terms, and the glossary describes the distinction.

Yes, but section 3.7.1.2 frequently uses the term "command group object" and includes sentences like

> In this case, since the different command group objects execute on different devices, the actions required to satisfy the requirements may be different

which seems imprecise to me. As I understand it, a command group is not an "object" but rather some abstract, implementation-defined set of actions that need to be performed in order to execute a command. A command group function object on the other hand is just some functor that is invoked on the host, not a device.

**Comment by gmlueck** [comment]
Yes, I agree that is imprecise.  We should use the terms consistently.

TBH, I'm not sure we need different glossary terms for "command" and "command group".  For example, I'm not sure which of those terms we should use in the sentence you quote.  However, I agree that "command group object" is wrong.
