### ISSUE TITLE
Unclear descriptions of max_work_item_sizes

### ISSUE THREAD

**Issue by Pennycook** [KhronosGroup/SYCL-Docs#310]
In Table 25. Device information descriptors, there are three `max_work_item_sizes` descriptors described like this:

> Returns the maximum number of work-items that are permitted of the work-group of the nd_range. The minimum value is (1) for devices that are not of device type info::device_type::custom.

What does "permitted of the work-group of the nd_range" mean?  It's unclear to me whether this is intended to return:

1. the maximum number of work-items that are permitted in each dimension of a work-group
2. the maximum number of work-items that are permitted in each dimension of an ND-range
3. the maximum number of work-groups that are permitted in each dimension of an ND-range (probably not this one)

Does anybody know what the intent was here?

**Comment by tomdeakin** [comment]
Equiv. in OpenCL. Should match OpenCL. PR for option 1. to align.
