### ISSUE TITLE
`sycl::error_category_for` function is not described

### ISSUE THREAD

**Issue by Melirius** [KhronosGroup/SYCL-Docs#315]
`sycl::error_category_for` function is not described in the documentation. 

_4.13.1.4. Asynchronous errors with a secondary queue_ contains an example of its usage, so it is clear what it does, but no formal description of it is present in _4.13.2. Exception class interface_.

I think the description should be added after _Table 140. SYCL error code helper functions_.

**Comment by gmlueck** [comment]
See #164 for more information on this topic.

**Comment by tomdeakin** [comment]
Bypass test for now until #164 makes progress.
