### ISSUE TITLE
Description of common functions

### ISSUE THREAD

**Issue by Melirius** [KhronosGroup/SYCL-Docs#321]
It is written in the spec 4.17.7 that "The built-in functions can take as input float or optionally double and their vec and marray counterparts." However, in the table 179 further the functions are generally defined for `genfloat` inputs, so that by table 165 means that they are defined for `half` also.

Should this line then be rewritten as "The built-in functions can take as input float or optionally double and half and their vec and marray counterparts."?

And maybe functions like `genfloath max(genfloath x, sycl::half y)` should also be introduced to the spec?

**Comment by gmlueck** [comment]
> Should this line then be rewritten as "The built-in functions can take as input float or optionally double and half and their vec and marray counterparts."?

Yes, this is the intent.

> And maybe functions like `genfloath max(genfloath x, sycl::half y)` should also be introduced to the spec?

Yes, this seems to be an oversight.  The functions in this section all derive from OpenCL C, and OpenCL C does have these overloads for `half`.

**Comment by TApplencourt** [comment]
Should we also clarify that we can mix and match any type of `genfloat`? And if yes, what are the return types in this case? ( I guess the wider datatype)

For example, I got a question to day who asked if `fmax(sycl::marray<T,N> x, T y)` is valid?  My reading of the spec is "yes, and should return a marray` but not 100% sure.  Maybe worth clarifying.

**Comment by gmlueck** [comment]
The pseudo-type `sgenfloat` includes only the scalar types, so the prototype you show does not include `T fmax(T x, marray<T,N> y)`.  The intent of the spec is that when a pseudo-type name appears twice in the same function declaration, both occurrences are the same concrete type.  Therefore, `genfloat fmax(genfloat x, sgenfloat y)` means that we have functions like this:

```
float fmax(float x, float y)
marray<float,N> fmax(marray<float,N> x, float y)
vec<float,N> fmax(vec<float,N> x, float y)
```

and similarly for the other floating point types (`double` and `sycl::half`).

FWIW, I sometimes think that it was a mistake to use these pseudo-types in the SYCL spec because it requires a requires a very close reading of the spec to understand the intent.  It might be clearer if we just listed all of the overloads for these functions, though that would be more verbose.

**Comment by nscottnichols** [comment]
The pseudo-type language in the spec leads me to believe `marray<float,N> fmax(marray<float,N> x, double y)` is valid and mixing and matching different floating point types are allowed. Is there text clarifying, where in the case for `genfloat fmax(genfloat x, sgenfloat y)`, whether it should be `T1 fmax(T2 x, T3 y)` or `T4 fmax(T4 x, T5 y)`? In the first case, appropriate converters between the different possible `genfloat` combinations for `T1` and `T2` need to be available for the SYCL implementation. Also, does `T2` and `T3` (or `T4` and `T5`) need to have the same floating point type?

**Comment by TApplencourt** [comment]
I agree that using "standard C++ templating syntax" seems to be a good idea, maybe verbose but more straightforward. I guess we can use `enable if` if we want to be more concise.
 
If we have `genfloat fmax(genfloat x, sgenfloat y)`, I don't see why we cannot have `T fmax(T x, marray<T,N> y)`. This seems to be valid from the spec point of view.  We should forbid it.
Same if we do `fmax(marray<T,N1> x, marray<T,N2> x,  y)` where (`N1 != N2`). I guess in short `marray` add a lot of new restriction on how to mix type.

**Comment by gmlueck** [comment]
I think we should not use template syntax in the spec unless we expect these functions to behave like templates.  Internal issue [278](https://gitlab.khronos.org/sycl/Specification/-/issues/278) discusses this, and I think the consensus is trending that they should behave like overloads.

> Indeed sgenfloat include float to it should that also `marray<float,N>`

The pseudo-types are defined in [section 4.17.1](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_description_of_the_built_in_types_available_for_sycl_host_and_device).  To be sure, I think section 4.17 has many unclear things, but there is some formal definition of the pseudo types.

> Also for gentype fmax(gentype x, gentype y) what append to fmax(marray<T,N1> x, float marray<T,N2>). I guess nothing forbib it, but it seem wrong

This is one of the unclear things, but I think the intent is that when a single prototype has multiple occurrences of a pseudo-type (like `gentype`) then all occurrences are expected to be the same concrete type.  In your example `marray<T,N1>` and `marray<T,N2>` are different concrete types.

**Comment by nscottnichols** [comment]
> This is one of the unclear things, but I think the intent is that when a single prototype has multiple occurrences of a pseudo-type (like gentype) then all occurrences are expected to be the same concrete type. In your example marray<T,N1> and marray<T,N2> are different concrete types.

Intuitively this makes sense. Clarifying text should be added explicitly stating it, especially if we don't expect the functions to behave like templates.

**Comment by gmlueck** [comment]
Half support fully added to the common functions in #440
