### ISSUE TITLE
Expectations for maximum memory size

### ISSUE THREAD

**Issue by philipturner** [KhronosGroup/SYCL-Docs#333]
Are there any expectations for how much memory you can allocate in SYCL? I was working on a [draft for a USM implementation](https://github.com/philipturner/metal-usm), and originally had the following plan. Allocate a large Metal allocation taking up a sizeable chunk of device RAM (1/8 - 1/4). Divide that large allocation into smaller ones. This lets you subtract the buffer's base GPU VA from its actual CPU address, and easily translate between CPU and GPU address spaces in a kernel. However, the statically allocated buffer has a fixed size. It can't be larger, or else the user's computer would be unusable for other tasks. Also, running numerous SYCL apps simultaneously would make you run out of memory.

More investigation revealed a better solution, where you allocate chunks of at least 1/128 of device RAM. hipSYCL's interop of accessors and USM means even accessors must fall within the USM pool. Therefore, all allocations of all types can sum to ~127/128 of device RAM. This poses another problem. In Metal, a `MTLBuffer` can be automatically swapped to disk, expanding your usable memory size outside the bounds of device RAM. The "better solution" for my SYCL backend would prevent that from ever happening. For example, you could disable paging upon fetching the USM pointer belonging to an accessor. But you'd also have to copy the accessors's contents into the USM memory heap, harming performance.

Is there any expectation that SYCL devices can page their memory to disk and oversubscribe device RAM? What about my original plan - if another person implemented a similar idea, would that be acceptable?

**Comment by kevin-harms** [comment]
SYCL doesn't have any really have any requirements of how memory allocations is handled. This is left to the device specific drivers. The following [table](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_kinds_of_unified_shared_memory) has some details but it mostly refers to visibility/accessibility and only where memory may be located.
