### ISSUE TITLE
Address Space of Shared USM allocations

### ISSUE THREAD

**Issue by hdelan** [KhronosGroup/SYCL-Docs#369]
If I want to construct an `atomic_ref` with a ref type from a shared USM allocation ie using `malloc_shared`, then what address space should be used in the AS template parameter?

How shared USM works is specific to each platform and hardware, so sometimes the `global_space` may be valid, but other times it may not be. Would it be sensible to say that `atomic_ref`s of shared USM allocations should therefore only use the generic space?

Motivation: `atomic_ref<..., address_space::global_space>` does not work when reftype is in shared USM allocation for AMDGPU backend of DPC++. I am not sure if the implementation or the spec should be changed to clarify things.

**Comment by jinz2014** [comment]
Could the SYCL spec add paragraphs to explain
1 the meaning of a generic address space ? 
2 when a generic address space may be used in SYCL functions ?

**Comment by gmlueck** [comment]
I think the behavior you are seeing with the AMDGPU backend is a bug.  USM allocations are defined to be in the global address space.  See this statement in [section 3.8.1](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sub.section.memmodel.app):

> The application running on the host uses SYCL buffer objects using instances of the sycl::buffer class or USM allocation functions to allocate memory in the global address space, or can allocate specialized image memory using the sycl::unsampled_image and sycl::sampled_image classes.

@jinz2014

Re. 1: I have submitted #375 to clarify the SYCL specification.  Does this address your concern?
Re. 2: We recently clarified the address space template parameter to `atomic_ref` in #358.

**Comment by jinz2014** [comment]
Thank you for your replies. Is it right users can simply specify a generic address space for sycl::atomic_ref in a SYCL kernel for atomic operations over global or shared local memory?

**Comment by hdelan** [comment]
@gmlueck thanks for clarification. I will close this ticket

**Comment by gmlueck** [comment]
> Is it right users can simply specify a generic address space for sycl::atomic_ref in a SYCL kernel for atomic operations over global or shared local memory?

Yes.
