### ISSUE TITLE
Image accessor deduction tag constructors cannot deduce DataT

### ISSUE THREAD

**Issue by steffenlarsen** [KhronosGroup/SYCL-Docs#399]
In the SYCL 2020 specification, the `unsampled_image_accessor` and `sampled_image_accessor` accessors have constructors with deduction tags, together with sections describing the correlation between the deduction tags and template arguments on these classes.

However, the deduction tags do not specify the `DataT` template argument, which cannot be determined at compile-time as neither `unsampled_image` nor `sampled_image` contains that information. As such, the deduction tag constructors on `unsampled_image_accessor` and `sampled_image_accessor` cannot be implemented as defined.

**Comment by steffenlarsen** [comment]
Suggested solution: Remove the deduction tag constructors and change `get_access` and `get_host_access` on the image classes to take the required template arguments. Patch with this in https://github.com/KhronosGroup/SYCL-Docs/pull/400.

**Comment by tomdeakin** [comment]
Close as #400 is merged
