### ISSUE TITLE
Missing `reduction_using_atomic` querry?

### ISSUE THREAD

**Issue by TApplencourt** [KhronosGroup/SYCL-Docs#413]
1. Reduction can be implemented via atomic
2. Atomic have restriction on which USM memory allocation they can access. (see [usm_atomic_{host,shared}_allocations](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:device-aspects)  device aspect) 

Should we add a query to know if a reduction is implemented via reduction?
Or are we ok that spec implicitly mandates that reduction should work regardless of the type of memory aka atomic-free implementation?  This may require stronger concurrency requirements than currently supported (see nice @Pennycook  talk a syclcon!).

Relevant to CTS (https://github.com/KhronosGroup/SYCL-CTS/pull/618).

**Comment by Pennycook** [comment]
I think that implementations have sufficient wiggle-room here that we don't need a query like this.

The specification already says that:
> If ... a reduction variable is accessed directly during the lifetime of a reduction (e.g. via an accessor or USM pointer), the behavior is undefined.

and:
> An implementation may use an unspecified number of temporary variables inside of any reducer objects it creates.

If we mandate that reductions should work regardless of the type of memory the reduction variable was created from, implementations would still have a lot of options.  For example, if an implementation wanted to use an atomics-based reduction but could only support atomics to device memory, it would be legal to create a copy of the reduction variable in device memory, atomically update it during the reduction kernel, then copy the result back to the original user-provided memory when the kernel completes. Atomics-free reductions would be an option too (as you suggested), and there are probably some hybrid options (e.g. using atomics only at supported scopes).

**Comment by TApplencourt** [comment]
Thanks for the clarification. So the absence of this query is not a bug, it's a feature. Work for me! Will close the issue as resolved :) 

>If we mandate that reductions should work regardless of the type of memory the reduction variable was created from.

I think we implicitly mandated it (as we don't specify any restriction) Do you think we should add one sentence to clarify it? . As you demonstrated, it's implementable.
