### ISSUE TITLE
Clarify where an instance of the sub_group class can be used

### ISSUE THREAD

**Issue by KornevNikita** [KhronosGroup/SYCL-Docs#451]
The sub_group class does not contain any field, all calls to it's methods are replaced by built-in calls. Hence - there is no sense to use the instance of sub_group somewhere other than where it was instantiated.
As I know there is an idea to add a restriction to the specification regarding this.

**Comment by KornevNikita** [comment]
FYI @gmlueck @Pennycook @AlexeySachkov

**Comment by fraggamuffin** [comment]
write to memory then read back to a different work item, if you use that object, does not matter where it was constructed, always get back info about the calling work item
intent was to allow behaviour where everything just wraps
today they are all by value

**Comment by KornevNikita** [comment]
So, closing this as it probably won't fix
