### ISSUE TITLE
Are platforms required to contain at least one device?

### ISSUE THREAD

**Issue by psalz** [KhronosGroup/SYCL-Docs#459]
In section 3.7.1.1 "SYCL backend resources managed by the SYCL application" the spec [currently says](https://github.com/KhronosGroup/SYCL-Docs/blob/0722c71b17b82e096965e04c0e95a638ffee562e/adoc/chapters/architecture.adoc#sycl-backend-resources-managed-by-the-sycl-application) that (emphasis mine)

> 3. Devices: platforms provide **one or more** devices for executing SYCL kernels. In SYCL, a device is accessible through a sycl::device object.

This seems to imply that platforms have to always contain at least one device. However as far as I can tell, this is not stated explicitly anywhere else. If this is intentional, it should be stated more explicitly in sections 3.5 and 4.6.2.

At first glance however it seems to me that there is no real benefit in having this requirement, and I'd be in favor of removing it. It could be useful to enumerate all platforms that are available in theory, but don't have any available devices.

**Comment by psalz** [comment]
The use case I had in mind would be for example a SYCL installation that was compiled with CUDA support, but at runtime `CUDA_VISIBLE_DEVICES=""` is set. By allowing empty platforms one could see that CUDA support is enabled in principle at least, and that the reason for an NVIDIA GPU not showing up must be lying elsewhere.

Of course if that change would have far-fetching consequences as you point out, it might not be worth it. The above use case could in principle also be achieved through backends, although AFAIK there is currently no way of programmatically listing backends (nor their names, for that matter).

**Comment by TApplencourt** [comment]
I tend to agree with Greg, not sure the complexity added is worth it.

**Comment by keryell** [comment]
> I tend to agree with Greg, not sure if the added complexity is worth it.

On the other hand, filtering out platforms without any device requires some complexity instead of just returning the list of known platforms.

**Comment by psalz** [comment]
> I tend to agree with Greg, not sure if the added complexity is worth it.

That's fine with me, but do we agree that it should be stated more explicitly in sections 3.5 and/or 4.6.2?

**Comment by tomdeakin** [comment]
WG discussion Oct/5/23

**Comment by gmlueck** [comment]
Fixed with #468.
