### ISSUE TITLE
Missing description for `vec::operator~`?

### ISSUE THREAD

**Issue by AlexeySachkov** [KhronosGroup/SYCL-Docs#478]
Looking at [4.14.2.1. Vec interface](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_vec_interface), I can't find any description or mention of bitwise not operation support for `vec` class.

However, it is being tested by the CTS: [`tests/vector_operators/generate_vector_operators.py:L924`](https://github.com/KhronosGroup/SYCL-CTS/blob/eec8701491114d1930c90679ba5072dd2a5162cb/tests/vector_operators/generate_vector_operators.py#L924):

```
  resVec = ~testVec1;
  if (!check_vector_values(resVec, resArr)) {
    resAcc[0] = false;
  }
  resVec = ~testVec1.${swizzle};
  if (!check_vector_values(resVec, resArr)) {
    resAcc[0] = false;
  }
```

**Comment by gmlueck** [comment]
It's there in the spec.  Search for "operator~".

**Comment by AlexeySachkov** [comment]
Indeed, I was expecting to find it as part of one of generic `operatorOP` and didn't use "Find" to check. Apology for spam
