### ISSUE TITLE
set_final_data invalid default argument

### ISSUE THREAD

**Issue by StuartDAdams** [KhronosGroup/SYCL-Docs#52]
The documentation for the ```image``` and ```buffer``` class' ```set_final_data``` member functions contains incorrect default arguments. Both function declarations reference a nonexistent ```std::nullptr``` value instead of the ```nullptr``` keyword. This can be seen at the following locations:

https://github.com/KhronosGroup/SYCL-Docs/blob/4a2dff3a779ae6fa4a477b0f02002c6ab82a3088/latex/headers/image.h#L156

https://github.com/KhronosGroup/SYCL-Docs/blob/4a2dff3a779ae6fa4a477b0f02002c6ab82a3088/latex/headers/buffer.h#L105

https://github.com/KhronosGroup/SYCL-Docs/blob/924a9fb6c099c918b759da74c667470b804f8fea/latex/programming_interface.tex#L1978

https://github.com/KhronosGroup/SYCL-Docs/blob/924a9fb6c099c918b759da74c667470b804f8fea/latex/programming_interface.tex#L1357

**Comment by keryell** [comment]
Indeed!
We probably got confused with `std::nullptr_t`.
Would you mind to send a PR? :-)

**Comment by StuartDAdams** [comment]
No problem. Will do.

**Comment by keryell** [comment]
2020/03/24 meeting: gentle ping to @StuartDAdams

**Comment by StuartDAdams** [comment]
Ah. Thank you for reminding me of this, Ronan. I'll get on it as soon as I can.

**Comment by StuartDAdams** [comment]
https://github.com/KhronosGroup/SYCL-Docs/pull/84
