### ISSUE TITLE
Buffer reinterpret 1D range

### ISSUE THREAD

**Issue by ProGTX** [KhronosGroup/SYCL-Docs#65]
When reinterpreting to a buffer of dimension 1, the 1.2.1 spec allows only one way to specify the range, because of the following paragraph (Member functions for the buffer class):

```
Must throw an invalid_object_error SYCL exception if the total size in bytes represented by the type and range of the reinterpreted SYCL buffer does not equal the total size in bytes represented by the type and range of this SYCL buffer.
```

Example:
```cpp
buffer<int, 2> initial{range<2>{5, 6}};
buffer<float, 1> linear = initial.reinterpret<float, 1>(range<1>{initial.get_size() / sizeof(float)});
```

In this case it should be possible to just omit the range, because the SYCL runtime knows exactly what to do. If we also allow the dimensions parameter to be defaulted to the same one as the original buffer, it would simplify 1D buffers even further:
```cpp
buffer<int> initial{range<1>{16}};
buffer<float> linear_float = initial.reinterpret<float>();
buffer<char> linear_char = initial.reinterpret<char>();
```

**Comment by keryell** [comment]
That looks like a good improvement.

**Comment by ProGTX** [comment]
This won't be done for SYCL 1.2.1
