### ISSUE TITLE
Add queue(context, device) constructor overload

### ISSUE THREAD

**Issue by AerialMantis** [KhronosGroup/SYCL-Docs#71]
The specification doesn't provide the following queue constructor:

```
queue(const context &syclContext, const device &syclDevice, const property_list &propList = {});
```

The only alternative is to use:

```
queue(const context &syclContext, const device_selector &deviceSelector, const property_list &propList = {});
```

Having this constructor would be useful for any case where you have a device and a user constructed context and want to create a queue, but don't want to pay the cost of having the queue implicitly construct another context.

It would also be useful in interop cases where you have a device and an interop context or a user constructed context and an interop device.

**Comment by jbrodman** [comment]
It would be nice if queue also had a copy constructor that would instantiate a new queue with the existing queue's device, context, props, etc.

**Comment by mkinsner** [comment]
Internal Khronos reference: https://gitlab.khronos.org/sycl/Specification/merge_requests/377/diffs

**Comment by Ruyk** [comment]
> It would be nice if queue also had a copy constructor that would instantiate a new queue with the existing queue's device, context, props, etc.

Like
```cpp
auto newQueue = existingQueue.duplicate():
```
?

**Comment by Ruyk** [comment]
or 
```cpp
queue newQueue(myQueue);
```
?

**Comment by Ruyk** [comment]
Related: https://github.com/intel/llvm/pull/1080

**Comment by jbrodman** [comment]
> or
> 
> ```c++
> queue newQueue{myQueue};
> ```
> 
> ?

I think this form would be easier.

**Comment by AerialMantis** [comment]
> It would be nice if queue also had a copy constructor that would instantiate a new queue with the existing queue's device, context, props, etc.

How would this vary from the current copy constructor, would it construct a `queue` with the same context, device and properties, but construct a new underlying `cl_command_queue` rather than retaining that of the original `queue`?

**Comment by jbrodman** [comment]
Yes.  Good point that this gets in the way of the common ref semantics stuff.  Maybe the copy constructor form is too confusing then.

**Comment by mkinsner** [comment]
The queue constructor change is implemented with #72 

The copy constructor should be tracked separately.

**Comment by AerialMantis** [comment]
> The copy constructor should be tracked separately.

Yeah, maybe we should move this discussion to a new separate ticket.

**Comment by jbrodman** [comment]
Nah.  We're good.

**Comment by keryell** [comment]
> Yes. Good point that this gets in the way of the common ref semantics stuff. Maybe the copy constructor form is too confusing then.

Not at all. :-)
You will just teach that
```
sycl::queue same_q ( static_const<const queue&>(q) };
sycl::queue cloned_q { q };
```
Perhaps it is simpler to add a `.clone()` member function or whatever the ISO C++ direction group will suggest here...
