### ISSUE TITLE
OpenCL contexts should not be implicitly convertible to SYCL contexts

### ISSUE THREAD

**Issue by jwlawson** [KhronosGroup/SYCL-Docs#8]
An OpenCL Context can be implicitly converted to a SYCL context. The spec (v1.2.1r5) does not forbid it, as the constructor:
```cpp
context(cl_context clContext, async_handler asyncHandler = {});
```
is not marked explicit. This means the following is currently valid SYCL code:
```
#include <CL/cl.h>
#include <CL/sycl.hpp>

int use_sycl_context(cl::sycl::context sycl_context) {
  // Do something with context
  (void)sycl_context;
  return 0;
}

int use_cl_context(cl_context ocl_context) {
  return use_sycl_context(ocl_context);
}
```

I believe this is a bad idea, as a SYCL context constructor may involve a comparatively large amount of work beyond just initialising a cl_context pointer. If the conversion is only allowed to be explicit then a user must deliberately construct the SYCL context and so is much less likely to construct them when not expected.

**Comment by AerialMantis** [comment]
SYCL working group:
Agreed that this is a bug and that the constructor should be explicit.

**Comment by fraggamuffin** [comment]
Mar 24:
does this apply to other constructors as well
A PR would be good

**Comment by fraggamuffin** [comment]
the other fix only solves it for the queue but not the context
A PR to make it explicit is welcomed

**Comment by gmlueck** [comment]
I think this issue can be closed because we no longer have constructors that take OpenCL native objects.

@keryell: Can you close this?  (I don't have permission.)

**Comment by keryell** [comment]
> Can you close this? (I don't have permission.)

@gmlueck you are not in the KhronosGroup organization. You need to ask the Khronos Webmaster for this.
Then I can add you to the SYCL group admin.
