### ISSUE TITLE
Consider adding default constructor for cl::sycl::range

### ISSUE THREAD

**Issue by psalz** [KhronosGroup/SYCL-Docs#90]
Currently the spec does define a default constructor for `cl::sycl::id`, but not for ` cl::sycl::range` . I'm not sure whether this is intentional or an oversight, however it can be quite a hassle when trying to write generic code.

For example consider this:
```c++
template <int dimensions>
struct my_range_holder {  cl::sycl::range<dimensions> range; };
```

There is no easy way of writing a constructor for this struct, without having to resort to some kind of range-initialization functor, or `if constrexpr` in C++17, both of which are far from pretty.

This issue first came to my attention because the Intel implementation seems to be the only one that actually doesn't provide some kind of default constructor for `cl::sycl::range`  (thus "breaking" my code :)). I did a quick survey of the rest of the implementations, and it looks like everybody is doing something slightly different:

| Implementation |                     |
| -------------- | ------------------- |
| ComputeCpp     | Initializes to 1    |
| hipSYCL        | Initializes to 0    |
| triSYCL        | Does not initialize  |

Clearly this is not great for portability, and even if you decide not to add a default constructor, at least consider explicitly deleting it in the spec. In my opinion, initializing ranges with 1, as ComputeCpp is doing, seems to be the most natural solution.

**Comment by keryell** [comment]
We have discussion this in the past. Perhaps it is the right time to discuss again. Adding this on the agenda of a future meeting.

The `(1,1,1)` has some interest but at the end it might not be very common in C++.
Why do you assume there is 1 thing to do by default? Why not nothing to do if we are lazily optimistic? :-)
Furthermore it requires always some wok inside the default constructor to be done, which might be against efficiency in embedded system and HPC.

**Comment by nliber** [comment]
I agree there is a usability issue with the number of necessary constructor parameters being dependent of the template argument.

However, a default constructor that does nothing (uninitialized members) is adding a state to` range` that it cannot get into now, correct?  That makes code harder to reason about.  It also technically is a breaking change, because every use of range,  including assign-from but not including assign-to, now has a new precondition that it is not in the default constructed state.  And you cannot even query that state.

The following code would be broken:

```
vector<range<1>> vr(1);
vr.reserve(vr.capacity() + 1);  // This call is always correct w/o a default ctor that does nothing

```

**Comment by nliber** [comment]
Does:

```
template <int dimensions>
struct my_range_holder {  std::optional<cl::sycl::range<dimensions>> range; };

```
meet your needs?  Besides no changes to SYCL, it has the advantages that only people who need this functionality pay for it, and it is pretty minimal in terms of the amount of work in default construction (essentially it initializes a `bool`).

**Comment by psalz** [comment]
> The `(1,1,1)` has some interest but at the end it might not be very common in C++.
> Why do you assume there is 1 thing to do by default? Why not nothing to do if we are lazily optimistic? :-)

Ranges with one or more zero components always feel a bit weird to me. What exactly does it mean to execute a kernel over the range `(33, 0, 42)`? The `size()` of such a range is 0, and any buffer or accessor constructed over this range would also report a size of 0, which seems odd.

> Furthermore it requires always some wok inside the default constructor to be done, which might be against efficiency in embedded system and HPC.

Yes, but couldn't that exact argument also be made for `cl::sycl::id` then? Also we are talking initializing (at most) 3x 64 bit here, so I would argue it's an acceptable trade-off for the added convenience. The especially performance-conscious can also just fall back to the other constructors in most (all?) situations.

> However, a default constructor that does nothing (uninitialized members) is adding a state to range that it cannot get into now, correct? That makes code harder to reason about.

Yes, I should've clarified this a bit more; I'm not really advocating for adding a default constructor that leaves the range uninitialized. For the reasons you've pointed out, and given the fact that `cl::sycl::id` already default-constructs to `(0,0,0)`, I don't think that would be a good idea.

> Does [...] meet your needs?

While that would somewhat help in situations where I'd need `my_range_holder` to be default-constructible (maybe for use in some container), it ultimately just defers the construction to whenever I actually want to interact with that range (which, in a templated function, would again have me bend over backwards to do it).

**Comment by nliber** [comment]
Unless you need a range where all dimensions have the same size, I'm not seeing how default constructing to either all 0s or all 1s helps.  Could you elaborate?

**Comment by ProGTX** [comment]
How about having a "fill" constructor - one that initializes all values to the same number? From the example:
```cpp
template <int dimensions>
struct my_range_holder {  cl::sycl::range<dimensions> range{1}; };
```
That way there is no worrying what the default should be as you can just initialize it to any value you want.

[SYCL-CTS would also benefit](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-1.2.1/master/tests/common/common.h#L504) from this constructor.

**Comment by keryell** [comment]
triSYCL just recycles `std::array` semantics for `range` and `id`. So nothing really scary either there but I agree that default initialization might have surprising results, just like an automatic integer variable.

But it support value initialization so the code from above
```c++
std::vector<range<1>> vr(1);
vr.reserve(vr.capacity() + 1);
```
is not broken.

And `range { 33, 0, 42 }` means no work to be done or a buffer of size 0 expressed in complex (or probably a generic for some reason) way.

**Comment by psalz** [comment]
> Unless you need a range where all dimensions have the same size, I'm not seeing how default constructing to either all 0s or all 1s helps in the generic case. Could you elaborate?

It probably won't help in most cases. I'm arguing for having a default constructor to simplify the usage of `range` in generic cases. What values it is being initialized to is not that important to me, but I think it should be predictable (and as you pointed out, not indeterminate). Or am I missing something?

Really I only want to be able to write something like this:
```c++
template<int dimensions>
range<dimensions> delta(const id<dimensions>& a, const id<dimensions>& b) {
  range<dimensions> result;
  for(int i = 0; i < dimensions; ++i) {
    result[i] = b[i] - a[i];
  }
  return result;
}
```

> How about having a "fill" constructor - one that initializes all values to the same number?

I like that as well, but then maybe `id` should also get one?

> And range { 33, 0, 42 } means no work to be done or a buffer of size 0 expressed in complex (or probably a generic for some reason) way.

Fair enough. In my (limited) experience I would still see this as more of a fringe case, and expect you'd want 1s instead of 0s more often than not. But again, I think the actual value is of secondary importance.

**Comment by keryell** [comment]
To summarize I agree with your request to have a default constructor.
The main bike-shedding is whether the default initialization actually set an initial value or not, and if so what is this value.

**Comment by nliber** [comment]
There are many solutions to this problem.  My main concern is in avoiding accidental bugs.

Would we be better with a tagged constructor, such as:

```
struct tag_t { explicit tag_t() = default; };
//...
range(tag_t);

```
Generic code could easily use this.  We can even say that the `range` is put in a valid-but-unspecified state, and the burden is on users to overwrite it.

I'm not necessarily against adding a default constructor.  Rather, if we pick specific values for the constructor, it should be because this values are a very common use case that users would expect, and I haven't yet seen enough rationale for either all 0s or all 1s, and that different implementations picked different values is an argument against there existing a preferred value.

It makes sense that a default constructed `std::string` is empty, because that is a very common use case, and even new users who have never read the documentation expect that.  I'm not yet convinced we can say the same thing for `range`.

**Comment by fraggamuffin** [comment]
Discussed on apr 8 2021

**Comment by keryell** [comment]
I think having `range` as a regular type simpler. So an initialized to 0 seems more mathematical and can be used as is in `std::accumulate` or reduction/prefix operations.

**Comment by fraggamuffin** [comment]
we now allow empty ranges 
common use case is no default constructor, or no value or some default value
1. no default cst
2. default cst with no value
3. default cst with 0
4. default cst with 1
5. default cst with same value for all dimension

**Comment by keryell** [comment]
Point 5 is another story I think, like `sycl::range<3> { 2 }` producing `{ 2, 2, 2 }`.

**Comment by ProGTX** [comment]
For ComputeCpp the default of all 1 has always made the most sense in terms of iteration space, as you can reduce it to a single point, essentially turning a `parallel_for` into a `single_task`. Additionally, assuming all dimensions above your working ones default to 1 also works for index linearization equations - the existing ones for 2D and 3D, and would be relatively easy to extend to multiple dimensions. Even for the case of making the type more mathematical, it can be argued that we see it more as a multiplicative type instead of an additive one (which `id` would be).

But my main worry is that there is no consensus on what the default should be, because there are some good arguments for having it 0. So I think we need to focus on what the use cases should be. The two uses presented so far could use either value or just not have it initialized because it's overwritten later anyway. Constructing all dimensions with the same value would also be sufficient for these two use cases presented here. So we could start with that and then potentially set a default value based on more analysis.

**Comment by tomdeakin** [comment]
> Point 5 is another story I think, like `sycl::range<3> { 2 }` producing `{ 2, 2, 2 }`.

I don't like the behaviour. It looks like a typo in the template parameter. If we allow this to work, my initial suggestion would be for `sycl::range<3> { 2 }` to produce `{ 2, 1, 1 }`. I think that would be safer.

I think I prefer the argument that range is a multiplicative variable and should initialise (if at all ) to 1. Given it's used in the linearisation equation, both for memory access and iteration space, zeros here might cause bad things to happen.

**Comment by Pennycook** [comment]
> I don't like the behaviour. It looks like a typo in the template parameter. If we allow this to work, my initial suggestion would be for `sycl::range<3> { 2 }` to produce `{ 2, 1, 1 }`. I think that would be safer.

This is also dangerous, and might not line up with user expectations. `{ 2, 1, 1 }` makes 2 the slowest-moving dimension, giving bad (vectorization) performance on many implementations. If we allow this, then `{1, 1, 2}` may be better.

I agree that it looks like a typo, and I think this pattern will lead to more confusion than anything.

**Comment by tomdeakin** [comment]
> > I don't like the behaviour. It looks like a typo in the template parameter. If we allow this to work, my initial suggestion would be for `sycl::range<3> { 2 }` to produce `{ 2, 1, 1 }`. I think that would be safer.
> 
> This is also dangerous, and might not line up with user expectations. `{ 2, 1, 1 }` makes 2 the slowest-moving dimension, giving bad (vectorization) performance on many implementations. If we allow this, then `{1, 1, 2}` may be better.
> 
> I agree that it looks like a typo, and I think this pattern will lead to more confusion than anything.

Oops - of course, linearisation goes that way! I think this is enough evidence for how easy it is to mess this up. I now think we should disallow this syntax, i.e. error where the template value and the number of parameters do not match.

**Comment by psalz** [comment]
Taking a step back, my primary gripe with `range` not having a default constructor was that there is no uniform call (in terms of number of arguments) that one can use for initializing a `range` in a templated context. If solving this is the objective, there are other options we could consider besides adding a default constructor (and the "broadcasting" constructor mentioned above):

- Using a tag type `sycl::range<D>(sycl::initialize_all, 1)`
- Static factory functions, like
	- `sycl::range::all<D>(v)`, which initializes all components to `v`, or
	- `sycl::range::make<D>(1, 2, 3)`, which truncates the excess components (i.e., `make<2>(1,2,3) == range<2>(1,2)`).

Another pattern we found useful in Celerity is to define the following constants that implicitly convert to any range:

```c++
	struct {
		size_t value;
		operator sycl::range<1>() const { return {value}; }
		operator sycl::range<2>() const { return {value, value}; }
		operator sycl::range<3>() const { return {value, value, value}; }
	} inline constexpr zero_range{0}, unit_range{1};
```

**Comment by keryell** [comment]
I would prefer to just use a C++20 `constexpr std:ranges` interface instead of inventing new C++ coding style if we can.

**Comment by fraggamuffin** [comment]
Straw Vote at the F2F by experts to get a feeling:
1. no default cst
2. default cst with no value
3. default cst with 0 for all dim
4. default cst with 1 for all dim
5. default cst with same value for all dimension
6. default cst with 0,0,1; 
7. default cst with 1,1,value;
8. specify all the dimensions, then truncated to the resulting dimension

**Comment by keryell** [comment]
There is also the decision about default initialization vs value initialization.

**Comment by fraggamuffin** [comment]
computecpp is now default init to 0 for all dimensions like hipSYCL
use id as precedence
aiming for 2020 as there is no default constructor now
