### ISSUE TITLE
Possible error in SYCL specification document (1.2.1)

### ISSUE THREAD

**Issue by breyerml** [KhronosGroup/SYCL-Docs#96]
On page 87 at line 69 in the sycl::buffer interface overview the function signature is:
```
buffer(buffer<T, dimensions, AllocatorT> b, 
    const id<dimensions> &baseIndex,
    const range<dimensions> &subRange);
```
However later in the table on page 93 regarding the constructor the function signature is:
```
buffer(buffer<T, dimensions, AllocatorT> &b,
    const id<dimensions> & baseIndex,
    const range<dimensions> & subRange)
```

In the table the buffer b is passed **by reference** while in the interface overview its passed **by value**.
I guess one of the function definitions is wrong?

**Comment by ProGTX** [comment]
You're correct, thank you for spotting this, I've created a PR to fix it.

**Comment by keryell** [comment]
@ProGTX Thanks.
