### ISSUE TITLE
User adding symbols to sycl namespace

### ISSUE THREAD

**Issue by rolandschulz** [KhronosGroup/SYCL-Docs#97]
Currently the spec only specifies how the implementer should use the sycl namespace. Section 4.1  states that extension should go into vendor namespace and implementation details into `detail`. It doesn't put any restriction on user code. Is the user allowed to put anything in sycl namespace? I assume the intention is that this isn't allowed. It should be clarified.

**Comment by keryell** [comment]
Yes, we should prevent this, since it can break implementations and have various undefined behaviors.

**Comment by fraggamuffin** [comment]
already disallowed
done and close

**Comment by keryell** [comment]
Closed by https://github.com/KhronosGroup/SYCL-Docs/pull/268
