### ISSUE TITLE
Support specifying global offset in parallel_for_work_group

### ISSUE THREAD

**Issue by fknorr** [KhronosGroup/SYCL-Docs#99]
`handler::parallel_for(nd_range<>, ...)` and `handler::parallel_for(range<>, )` both support a global offset parameter by wich all work item ids passed to the kernel will be shifted. `handler::parallel_for_work_group` is missing such a parameter.

Specifying a global offset is useful for accessing only part of an index space without requiring manual index translation inside the kernel. This can be used to transparently split kernel executions into parts, e.g. for staying within device memory limits, all without modifying the actual kernel implementation.

As a practical motivation, we use offsets on `parallel_for` in our SYCL-based distributed memory runtime [Celerity](https://github.com/celerity/celerity-runtime). The addition of this parameter would allow us to efficiently implement shared-memory functionality on top of `parallel_for_work_group` as well. 

The primary goal of an offset parameter is to shift the global ids that are iterated within `parallel_for_work_item`. The offset can be specified either on the `parallel_for_work_group` or the `parallel_for_work_item` call. We prefer the former variant for our application.

When the offset is part of the call to `parallel_for_work_group`, it could be specified either in work items similar to `nd_range`, or in multiples of the local size. We advocate for the latter variant, since it allows shifting group indices instead of just altering the work-item id mapping. This makes a split invocation of `parallel_for_work_group` completely transparent to device code.

It might also be worth discussing if and how this applies to the implicitly-sized overload of `parallel_for_work_group`, although we do not see a use case for that variant at the moment. For the time being, we advocate for the parameter to be added to the explicit variant only.

**Comment by keryell** [comment]
The current strategy is to get rid of offsets in SYCL and to rely on generic programming to address your "unchanged kernel" problem.
The offsets were imported from OpenCL when in fixed C API it might make sense.
In generic C++ and without OpenCL it makes less sense and you can generalize the concept to not only translations (block-cyclic distributions, etc.).
